[theme]
# Trava o sistema no modo escuro para evitar componentes brancos indesejados
base = "dark"

# Cor dos botões principais e elementos de destaque (Azul Corporativo)
primaryColor = "#2563EB"

# Fundo geral da tela (Cinza e moderno)
backgroundColor = "#F0F4F8" #D1D5DB" #FFFF00" #(amarelo)

# Fundo da barra lateral e dos campos de texto (Cinza-azulado discreto e elegante)
secondaryBackgroundColor = "#1E293B"

# Cor padrão do texto (Branco suave para excelente legibilidade)
textColor = "#F1F5F9"

font = "sans serif"
