[theme]
base = "light"
primaryColor = "#2563EB"
backgroundColor = "#F0F4F8"          # Fundo geral da página (Cinza suave)
secondaryBackgroundColor = "#FFFFFF" # Fundo interno de cards, formulários e modais
textColor = "#0F172A"                 # Cor dos textos principais
font = "sans serif"
